version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    # O Docker Compose vai ler o .env e injetar estas variáveis
    #'DATABASE_URL' será lida automaticamente pelo Postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: django_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Informa ao container para usar as variáveis do .env
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: